"""Aggregate per-task results into precision / recall / cost / latency."""
from __future__ import annotations

import json
from collections import defaultdict
from collections.abc import Iterable
from dataclasses import asdict, dataclass
from pathlib import Path
from statistics import mean

from bench.ground_truth import BugSignal, is_true_positive
from bench.types import PassAResult


@dataclass
class ToolScore:
    tool: str
    n_tasks: int
    total_findings: int
    true_positives: int
    false_positives: int
    bugs_known: int
    bugs_caught: int
    precision: float
    recall: float
    avg_setup_seconds: float
    avg_task_seconds: float
    total_tokens_in: int
    total_tokens_out: int
    total_cost_usd: float
    failures: int


def score_pass_a(
    results: Iterable[PassAResult],
    signals_by_commit: dict[str, list[BugSignal]],
) -> list[ToolScore]:
    by_tool: dict[str, list[PassAResult]] = defaultdict(list)
    for r in results:
        by_tool[r.tool].append(r)

    out: list[ToolScore] = []
    for tool, runs in by_tool.items():
        tp = 0
        fp = 0
        total_findings = 0
        bugs_known = 0
        bugs_caught = 0
        failures = 0
        for r in runs:
            if r.metrics.failed:
                failures += 1
                continue
            signals = signals_by_commit.get(r.commit_sha, [])
            commit_had_bug = bool(signals)
            if commit_had_bug:
                bugs_known += 1
            caught_this_commit = False
            for f in r.findings:
                total_findings += 1
                if is_true_positive(
                    signals=signals, finding_file=f.file, finding_line=f.line_start,
                ):
                    tp += 1
                    caught_this_commit = True
                else:
                    fp += 1
            if commit_had_bug and caught_this_commit:
                bugs_caught += 1

        precision = tp / total_findings if total_findings else 0.0
        recall = bugs_caught / bugs_known if bugs_known else 0.0
        ok_runs = [r for r in runs if not r.metrics.failed]
        out.append(
            ToolScore(
                tool=tool,
                n_tasks=len(runs),
                total_findings=total_findings,
                true_positives=tp,
                false_positives=fp,
                bugs_known=bugs_known,
                bugs_caught=bugs_caught,
                precision=round(precision, 3),
                recall=round(recall, 3),
                avg_setup_seconds=round(mean([r.metrics.setup_seconds for r in ok_runs]) if ok_runs else 0.0, 2),
                avg_task_seconds=round(mean([r.metrics.task_seconds for r in ok_runs]) if ok_runs else 0.0, 2),
                total_tokens_in=sum(r.metrics.tokens_in for r in ok_runs),
                total_tokens_out=sum(r.metrics.tokens_out for r in ok_runs),
                total_cost_usd=round(sum(r.metrics.cost_usd for r in ok_runs), 4),
                failures=failures,
            )
        )
    return out


def write_results_md(scores: list[ToolScore], out_path: Path, *, run_id: str) -> None:
    lines: list[str] = [
        f"# Benchmark results — run `{run_id}`",
        "",
        "Generated by `codegraph bench run`. Raw per-task data lives in `raw.jsonl`.",
        "",
        "## Pass A — Review the diff",
        "",
        "| Tool | Tasks | Findings | TP | FP | Bugs known | Bugs caught | Precision | Recall | Avg setup (s) | Avg task (s) | Tokens in | Tokens out | Cost (USD) | Failures |",
        "|------|------:|---------:|---:|---:|-----------:|------------:|----------:|-------:|--------------:|-------------:|----------:|-----------:|-----------:|---------:|",
    ]
    for s in sorted(scores, key=lambda x: x.tool):
        lines.append(
            f"| `{s.tool}` | {s.n_tasks} | {s.total_findings} | {s.true_positives} | "
            f"{s.false_positives} | {s.bugs_known} | {s.bugs_caught} | "
            f"{s.precision} | {s.recall} | {s.avg_setup_seconds} | {s.avg_task_seconds} | "
            f"{s.total_tokens_in} | {s.total_tokens_out} | {s.total_cost_usd} | {s.failures} |"
        )
    lines.extend([
        "",
        "## Methodology",
        "",
        "- Ground truth is heuristic: a finding is a TP if it overlaps (same file) with "
        "a follow-up `fix`/`bug`/`revert` commit within 30 days, or with a revert of the target commit.",
        "- See `bench/README.md` for full methodology and known limitations.",
        "- Re-score from `raw.jsonl` without re-spending API calls: `codegraph bench rescore --run-id " + run_id + "`.",
        "",
    ])
    out_path.write_text("\n".join(lines))


def dump_raw(results: list[PassAResult], out_path: Path) -> None:
    with out_path.open("w") as f:
        for r in results:
            f.write(json.dumps({
                "tool": r.tool,
                "repo": r.repo,
                "commit_sha": r.commit_sha,
                "findings": [
                    {
                        "file": x.file,
                        "line_start": x.line_start,
                        "line_end": x.line_end,
                        "severity": x.severity,
                        "title": x.title,
                        "body": x.body,
                    }
                    for x in r.findings
                ],
                "metrics": asdict(r.metrics),
            }) + "\n")
